### ISSUE TITLE
Premissions

### ISSUE THREAD

**Issue by awigg** [DanKub/PasswordGen#1]
Could you explain, why you need the following permissions?

1. Download files and read and modify the browser’s download history
2. Access your data for publicsuffix.org

**Comment by DanKub** [comment]
1. User is able to export generator preferences and stored rules into JSON file. For this functionality I used Downloads API, which requires _"downloads"_ permission. The API is described [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads).
If you want, you can view how it is implemented in the [source code](https://github.com/DanKub/PasswordGen/blob/master/sources/options/options.js) - function _exportSettings_.

2. For the correct recognition of top level domain names is used [Public Suffix List](https://publicsuffix.org/learn/). Since the list can be periodically changed, extension keeps full copy of the list no older than one month for the correct functionality. If stored offline version of the list is outdated, extension automatically tries to download latest version of the PSL. If you want, you can view how it is implemented in the [source code](https://github.com/DanKub/PasswordGen/blob/master/sources/background/background.js). Thats why I need access to publicsuffix.org.

**Comment by awigg** [comment]
Thank you. This was very helpful.
